### ISSUE TITLE
warnings from homebrew

### ISSUE THREAD

**Issue by bturrubiates** [b4b4r07/homebrew-gomi#1]
Got these warnings after running `brew upgrade`:

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/b4b4r07/homebrew-gomi/gomi.rb:7:in `<class:Gomi>'
Please report this to the b4b4r07/gomi tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/b4b4r07/homebrew-gomi/gomi.rb:7:in `<class:Gomi>'
Please report this to the b4b4r07/gomi tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/b4b4r07/homebrew-gomi/gomi.rb:7:in `<class:Gomi>'
Please report this to the b4b4r07/gomi tap!
```

**Comment by babarot** [comment]
Thanks, but I'm afraid I can't fix those errors for a while because I'm caught up in another work everyday. Instead of that, I recommend this installation of using [zplug](https://github.com/zplug/zplug):

``` zsh
zplug "b4b4r07/gomi", \
    from:gh-r, \
    as:command, \
    use:"*${(L)$(uname -s)}*amd64*", \
    rename-to:gomi
```

**Comment by bturrubiates** [comment]
> Thanks, but I'm afraid I can't fix those errors for a while because I'm caught up in another work everyday. Instead of that, I recommend this installation of using zplug:

Okay, thanks!
